import { Jimp } from "jimp";
import { describe, expect, it } from "vitest";
import {
  MAX_VISION_DIMENSION,
  isAnimatedWebp,
  normalizeImageToDataUrls,
  sniffImageFormat,
} from "../src/image-format.js";

/** A real, valid PNG generated by jimp (avoids hand-rolled base64 mistakes). */
async function makePng(): Promise<Buffer> {
  const img = new Jimp({ width: 4, height: 4, color: 0x00ff00ff });
  return img.getBuffer("image/png");
}

/** A real, valid PNG with translucent pixels (alpha must keep it PNG). */
async function makeAlphaPng(): Promise<Buffer> {
  const img = new Jimp({ width: 4, height: 4, color: 0x00ff0080 });
  return img.getBuffer("image/png");
}

/** A real, valid JPEG generated by jimp. */
async function makeJpeg(): Promise<Buffer> {
  const img = new Jimp({ width: 4, height: 4, color: 0x0000ffff });
  return img.getBuffer("image/jpeg", { quality: 90 });
}

describe("sniffImageFormat", () => {
  it("detects PNG, JPEG, GIF and WebP from magic bytes", async () => {
    const png = await makePng();
    expect(sniffImageFormat(png)).toBe("png");
    const jpeg = await makeJpeg();
    expect(sniffImageFormat(jpeg)).toBe("jpeg");
    expect(sniffImageFormat(Buffer.from("GIF89a....", "utf8"))).toBe("gif");
    const webp = Buffer.concat([Buffer.from("RIFFxxxxWEBP", "utf8"), Buffer.alloc(8)]);
    expect(sniffImageFormat(webp)).toBe("webp");
  });

  it("returns undefined for non-raster / empty input", () => {
    expect(sniffImageFormat(Buffer.from("hello world", "utf8"))).toBeUndefined();
    expect(sniffImageFormat(Buffer.alloc(0))).toBeUndefined();
  });
});

/** Build a minimal RIFF/WEBP container with the given top-level chunks. The
 *  bytes only need to be structurally correct for the sniff + animation walker
 *  (no real pixels — jimp can't produce WebP anyway). */
function makeWebp(chunks: Array<{ fourcc: string; payload: Buffer }>): Buffer {
  const body = Buffer.concat(
    chunks.map((c) => {
      const size = Buffer.alloc(4);
      size.writeUInt32LE(c.payload.length, 0);
      const pad = c.payload.length % 2 === 1 ? Buffer.alloc(1) : Buffer.alloc(0);
      return Buffer.concat([Buffer.from(c.fourcc, "ascii"), size, c.payload, pad]);
    }),
  );
  const riffSize = Buffer.alloc(4);
  riffSize.writeUInt32LE(body.length, 0);
  return Buffer.concat([
    Buffer.from("RIFF", "ascii"),
    riffSize,
    Buffer.from("WEBP", "ascii"),
    body,
  ]);
}

const STATIC_WEBP = makeWebp([{ fourcc: "VP8 ", payload: Buffer.alloc(8) }]);
const STATIC_WEBP_EXTENDED = makeWebp([{ fourcc: "VP8X", payload: Buffer.alloc(10) }]);
// Synthetic animated container (structurally correct, garbage pixels) — enough
// to exercise the animation detector, but not decodable by any image lib.
const ANIMATED_WEBP = makeWebp([
  { fourcc: "VP8X", payload: Buffer.alloc(10) },
  { fourcc: "ANIM", payload: Buffer.alloc(6) },
  { fourcc: "ANMF", payload: Buffer.alloc(16) },
]);
// A real 2-frame animated WebP (generated by Pillow) — sharp must decode the
// first frame from this.
const REAL_ANIMATED_WEBP = Buffer.from(
  "UklGRsoAAABXRUJQVlA4WAoAAAACAAAAAwAAAwAAQU5JTQYAAAAAAAAAAABBTk1GSgAAAAAAAAAAAAMAAAMAAGQAAAJWUDggMgAAADABAJ0BKgQABAABQCYloAADcAD+8ut///mwP/bz/wR6Af//0uD//pcH//S4P/SkAAAAQU5NRkwAAAAAAAAAAAADAAADAABkAAAAVlA4IDQAAAA0AQCdASoEAAQAAAAmJaAAA3AA/ukiH//3nz//ufP/+58/6M///yn7//I4//8jj/5QIAAA",
  "base64",
);
// A real single-frame (static) WebP (generated by Pillow) — must also convert
// to PNG, since the vision API rejects WebP regardless of animation.
const REAL_STATIC_WEBP = Buffer.from(
  "UklGRi4AAABXRUJQVlA4ICIAAABwAQCdASoIAAgAAUAmJZQCdAFAAAD+/DeBV/fU6D4r4AAA",
  "base64",
);

describe("isAnimatedWebp", () => {
  it("flags an animated WebP (ANIM / ANMF chunks) as animated", () => {
    expect(sniffImageFormat(ANIMATED_WEBP)).toBe("webp");
    expect(isAnimatedWebp(ANIMATED_WEBP)).toBe(true);
  });

  it("treats a lone lossy / lossless / extended WebP as static", () => {
    expect(isAnimatedWebp(STATIC_WEBP)).toBe(false);
    expect(isAnimatedWebp(STATIC_WEBP_EXTENDED)).toBe(false);
  });

  it("is false for non-WebP input", () => {
    expect(isAnimatedWebp(Buffer.from("hello", "ascii"))).toBe(false);
    expect(isAnimatedWebp(Buffer.alloc(0))).toBe(false);
  });
});

describe("normalizeImageToDataUrls", () => {
  it("re-encodes an opaque PNG as JPEG so lossless bytes don't bloat the payload", async () => {
    const png = await makePng();
    const res = await normalizeImageToDataUrls(png);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime).toBe("image/jpeg");
    expect(res.dataUrls).toHaveLength(1);
    const url = res.dataUrls[0]!;
    expect(url.startsWith("data:image/jpeg;base64,")).toBe(true);
    // Round-trip: the data URL must decode back to a sniffable JPEG.
    const decoded = Buffer.from(url.split(",")[1]!, "base64");
    expect(sniffImageFormat(decoded)).toBe("jpeg");
  });

  it("keeps a translucent PNG as PNG (JPEG carries no alpha)", async () => {
    const res = await normalizeImageToDataUrls(await makeAlphaPng());
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime).toBe("image/png");
    expect(res.dataUrls[0]!.startsWith("data:image/png;base64,")).toBe(true);
  });

  it("passes through an already-valid JPEG without re-encoding", async () => {
    const jpeg = await makeJpeg();
    const res = await normalizeImageToDataUrls(jpeg);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime).toBe("image/jpeg");
    expect(res.dataUrls[0]!.startsWith("data:image/jpeg;base64,")).toBe(true);
  });

  it("converts a real static WebP into an accepted opaque format (renamed .png still sniffed as webp)", async () => {
    const res = await normalizeImageToDataUrls(REAL_STATIC_WEBP);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime === "image/jpeg" || res.mime === "image/png").toBe(true);
    const decoded = Buffer.from(res.dataUrls[0]!.split(",")[1]!, "base64");
    expect(sniffImageFormat(decoded)).toBe(res.mime === "image/jpeg" ? "jpeg" : "png");
  });

  it("falls back to an error when a WebP can't be decoded", async () => {
    // Structurally-webp bytes with no decodable pixels.
    const webp = Buffer.concat([Buffer.from("RIFFxxxxWEBP", "utf8"), Buffer.alloc(8)]);
    const res = await normalizeImageToDataUrls(webp);
    expect(res.ok).toBe(false);
    if (res.ok) return;
    expect(res.message).toMatch(/WebP could not be decoded/i);
  });

  it("extracts the first frame of a real animated WebP into an accepted format", async () => {
    const res = await normalizeImageToDataUrls(REAL_ANIMATED_WEBP);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.mime === "image/jpeg" || res.mime === "image/png").toBe(true);
    const decoded = Buffer.from(res.dataUrls[0]!.split(",")[1]!, "base64");
    expect(sniffImageFormat(decoded)).toBe(res.mime === "image/jpeg" ? "jpeg" : "png");
  });

  it("falls back to an error when an animated WebP can't be decoded", async () => {
    // Synthetic container with garbage frame pixels — sharp can't decode it.
    const res = await normalizeImageToDataUrls(ANIMATED_WEBP);
    expect(res.ok).toBe(false);
    if (res.ok) return;
    expect(res.message).toMatch(/WebP could not be decoded/i);
  });

  it("rejects garbage bytes with an error instead of shipping them", async () => {
    const res = await normalizeImageToDataUrls(Buffer.from("definitely not an image", "utf8"));
    expect(res.ok).toBe(false);
    if (res.ok) return;
    expect(res.message).toMatch(/not a decodable image|image is empty/);
  });

  it("rejects empty input", async () => {
    const res = await normalizeImageToDataUrls(Buffer.alloc(0));
    expect(res.ok).toBe(false);
  });

  it("splits an image taller than the vision cap into accepted tiles", async () => {
    // DeepSeek 400s on any side above 8192; a full-page screenshot can exceed it.
    // Only the over-cap height matters to the assertion, so a narrow fixture keeps
    // the pure-JS PNG codec fast (same trick as the within-cap test below).
    const img = new Jimp({ width: 16, height: MAX_VISION_DIMENSION + 2000, color: 0x3366ccff });
    const png = await img.getBuffer("image/png");
    const res = await normalizeImageToDataUrls(png);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.dataUrls.length).toBeGreaterThanOrEqual(2);
    for (const url of res.dataUrls) {
      const decoded = Buffer.from(url.split(",")[1]!, "base64");
      const tile = await Jimp.fromBuffer(decoded);
      expect(Math.max(tile.width, tile.height)).toBeLessThanOrEqual(MAX_VISION_DIMENSION);
    }
  });

  it("keeps a within-cap image as a single data URL", async () => {
    // Size is irrelevant to the assertion (any within-cap image passes through
    // un-tiled), so a small fixture keeps the pure-JS PNG encode fast.
    const img = new Jimp({ width: 1024, height: 1024, color: 0x3366ccff });
    const png = await img.getBuffer("image/png");
    const res = await normalizeImageToDataUrls(png);
    expect(res.ok).toBe(true);
    if (!res.ok) return;
    expect(res.dataUrls).toHaveLength(1);
  });
});
