import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Jimp } from "jimp";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ToolRegistry } from "../src/tools.js";
import { registerSeeImageTool } from "../src/tools/see-image.js";

/** A real, valid PNG data URL (generated by jimp) — the header-only constant the
 *  old tests used gets rejected by byte-sniffing now. */
async function realPngDataUrl(): Promise<string> {
  const img = new Jimp({ width: 4, height: 4, color: 0x00ff00ff });
  const buf = await img.getBuffer("image/png");
  return `data:image/png;base64,${buf.toString("base64")}`;
}

const DATA_URL = "data:image/png;base64,iVBORw0KGgo=";

describe("see_image", () => {
  let root: string;
  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), "see-image-"));
  });
  afterEach(() => {
    rmSync(root, { recursive: true, force: true });
  });

  function registry(): ToolRegistry {
    const tools = new ToolRegistry();
    registerSeeImageTool(tools);
    return tools;
  }

  it("confirms the images attached to the current turn (via dispatch ctx)", async () => {
    const out = await registry().dispatch("see_image", "{}", { images: [DATA_URL] });
    expect(out).toContain("1 image(s) attached to the current turn");
    expect(out).toContain("visible to you directly");
  });

  it("counts multiple attached images", async () => {
    const out = await registry().dispatch("see_image", "{}", {
      images: [DATA_URL, DATA_URL],
    });
    expect(out).toContain("2 image(s) attached");
  });

  it("confirms a data: URL passed as path (returns image_url content parts)", async () => {
    const url = await realPngDataUrl();
    const out = await registry().dispatch("see_image", JSON.stringify({ path: url }));
    expect(Array.isArray(out)).toBe(true);
    const parts = out as Array<{ type: string; text?: string; image_url?: { url: string } }>;
    const text = parts.find((p) => p.type === "text")?.text ?? "";
    expect(text).toContain("Image loaded at data URL");
    const image = parts.find((p) => p.type === "image_url");
    expect(image?.image_url?.url?.startsWith("data:image/png;base64,")).toBe(true);
  });

  it("loads an existing image file into an image_url part (actual pixels)", async () => {
    const bytes = await new Jimp({ width: 4, height: 4, color: 0x00ff00ff }).getBuffer("image/png");
    writeFileSync(join(root, "shot.png"), bytes);
    const out = await registry().dispatch("see_image", JSON.stringify({ path: "shot.png" }), {
      rootDir: root,
    });
    expect(Array.isArray(out)).toBe(true);
    const parts = out as Array<{ type: string; text?: string; image_url?: { url: string } }>;
    const text = parts.find((p) => p.type === "text")?.text ?? "";
    expect(text).toContain(`Image loaded at ${join(root, "shot.png")}`);
    const image = parts.find((p) => p.type === "image_url");
    // The data URL must carry real PNG bytes so the vision model actually sees them.
    expect(image?.image_url?.url?.startsWith("data:image/png;base64,")).toBe(true);
  });

  it("resolves a relative path against the tool root", async () => {
    const sub = join(root, "shots");
    mkdirSync(sub, { recursive: true });
    writeFileSync(
      join(sub, "a.jpeg"),
      await new Jimp({ width: 4, height: 4, color: 0x0000ffff }).getBuffer("image/jpeg", {
        quality: 90,
      }),
    );
    const out = await registry().dispatch("see_image", JSON.stringify({ path: "shots/a.jpeg" }), {
      rootDir: root,
    });
    expect(Array.isArray(out)).toBe(true);
    const parts = out as Array<{ type: string; text?: string; image_url?: { url: string } }>;
    const text = parts.find((p) => p.type === "text")?.text ?? "";
    expect(text).toContain("Image loaded at");
    expect(text).toContain(join("shots", "a.jpeg"));
    expect(parts.some((p) => p.type === "image_url")).toBe(true);
  });

  it("rejects non-image file bytes (does not trust the extension)", async () => {
    // A `.png` suffix on non-image bytes must be rejected by byte sniffing,
    // proving the extension is never the source of truth.
    writeFileSync(join(root, "fake.png"), "definitely not an image", "utf8");
    const out = await registry().dispatch("see_image", JSON.stringify({ path: "fake.png" }), {
      rootDir: root,
    });
    expect(out).toContain("not a decodable image");
  });

  it("rejects missing files", async () => {
    const out = await registry().dispatch("see_image", JSON.stringify({ path: "missing.png" }), {
      rootDir: root,
    });
    expect(out).toContain("no such image file");
  });

  it("tells the model when nothing is available", async () => {
    const out = await registry().dispatch("see_image", "{}");
    expect(out).toContain("no image available");
    expect(out).toContain("no `path` was given");
  });

  it("is safe in plan mode (readOnly)", async () => {
    const tools = registry();
    tools.setPlanMode(true);
    const out = await tools.dispatch("see_image", "{}", { images: [DATA_URL] });
    expect(out).toContain("1 image(s) attached");
  });
});
