// Shared App-state stub for reducer-level tests of `desktop/src/App`.
// The full State shape is large (quota blocks, memory panels, turn status);
// tests previously hand-rolled this literal in three places. This is the one
// copy, mirroring the App.test.ts superset: add new State keys here when
// App.tsx grows them, or the delegating factories fail typecheck loudly.
// `overrides` shallow-merges on top of the defaults.
import type { reduce } from "../../desktop/src/App.js";

export type AppState = Parameters<typeof reduce>[0];

export function baseAppState(overrides: Partial<AppState> = {}): AppState {
  return {
    ready: false,
    needsSetup: false,
    busy: false,
    model: "deepseek-v4-flash",
    currentSession: "demo",
    messages: [],
    pendingConfirms: [],
    pendingPathAccess: [],
    pendingChoices: [],
    pendingPlans: [],
    pendingCheckpoints: [],
    pendingRevisions: [],
    activePlan: null,
    usage: {
      totalCostUsd: 0,
      lastCallCostUsd: 0,
      totalPromptTokens: 0,
      totalCompletionTokens: 0,
      cacheHitTokens: 0,
      cacheMissTokens: 0,
      lastCallCacheHit: null,
      lastCallCacheMiss: null,
      reservedTokens: 0,
      liveLogTokens: 0,
    },
    sessions: [],
    sessionsEpoch: "",
    sessionsRevision: 0,
    workspaceInitializationRevision: 0,
    pendingSessionDeletes: [],
    settings: null,
    balance: null,
    codexQuota: null,
    codexQuotaRefreshing: false,
    codexQuotaReason: null,
    ollamaQuota: null,
    ollamaQuotaRefreshing: false,
    ollamaQuotaReason: null,
    antigravityQuota: null,
    antigravityQuotaRefreshing: false,
    antigravityQuotaReason: null,
    zaiQuota: null,
    zaiQuotaRefreshing: false,
    zaiQuotaReason: null,
    opencodeQuota: null,
    opencodeQuotaRefreshing: false,
    opencodeQuotaReason: null,
    mentionResults: null,
    mentionPreview: null,
    mcpSpecs: [],
    mcpBridged: false,
    mcpExtensionStatus: null,
    mcpExtensionCheck: null,
    mailAuth: null,
    playwrightBrowserInstall: null,
    skills: [],
    sessionFiles: [],
    memory: [],
    memoryDetail: null,
    memoryResult: null,
    memoryExport: null,
    contextRaw: null,
    jobs: [],
    activeSkill: null,
    lastTurnOutcome: null,
    queuedSends: [],
    retryNonce: 0,
    oauthWaiting: false,
    antigravityOAuthWaiting: false,
    opencodeOAuthWaiting: false,
    turnStatus: null,
    turnStatusTool: null,
    turnLastEventMs: 0,
    turnElapsedMs: 0,
    ...overrides,
  };
}
